### ISSUE TITLE
Why is there no noise added in DDPG?

### ISSUE THREAD

**Issue by Kchu** [sfujim/TD3#12]
Thank you very much for your code, which is very clean and effective. But I have a question: DDPG mentioned the use of noise, why didn't you add noise to DDPG?

**Comment by Kchu** [comment]
And also, I find that it's lack of normalization  and denormalization of states...

**Comment by sfujim** [comment]
This was discussed in more detail over email, but I'm adding this response in case somebody else wonders similar things. 

Noise is added for line 199 in main.py. Normalization is not included as mentioned in the supplementary of the paper (we did not find it improved performance). The baseline used in the paper was from OpenAI baselines which uses normalization.
