### ISSUE TITLE
What is the reason behind to modify the DDPG implementation?

### ISSUE THREAD

**Issue by noklam** [sfujim/TD3#15]
I notice that in your paper **C. DDPG Network and Hyper-parameter Comparison** mention that the DDPG architecture is different from OpenAI Baseline. Is there any specific reason or intuition behind this? Thank you.

![image](https://user-images.githubusercontent.com/18221871/66754148-eaff1900-eec7-11e9-9d1b-4b8663e4c3c2.png)

![image](https://user-images.githubusercontent.com/18221871/66754240-213c9880-eec8-11e9-9d35-3bc30af473c5.png)

Fujimoto, S., Van Hoof, H., & Meger, D. (2018). Addressing Function Approximation Error in Actor-Critic Methods. 35th International Conference on Machine Learning, ICML 2018, 4, 2587–2601.

**Comment by sfujim** [comment]
OurDDPG exists to compare the algorithmic changes from DDPG to TD3, while keeping hyper-parameters and architectures fixed. We adjusted the architecture of TD3/OurDDPG from OpenAI baselines to have state-action input on the first layer mainly for simplicity, but we did find it improved performance somewhat as well when combined with the other changes.

**Comment by noklam** [comment]
Thanks for your reply, I feel it is more natural to put state-action in the first layer as well.

By the way, I think there is a type in "Our Ctiric Architecture", the second layer should be (400, 300) instead of (action dim + 400, 300)?
