### ISSUE TITLE
Replay Buffer Sampling

### ISSUE THREAD

**Issue by rvy11** [sfujim/TD3#17]
In the utils.py file, the sample method in the ReplayBuffer class generates a list of random indices to pull out a batch of transitions from the current replay buffer with the following line of code:

`ind = np.random.randint(0, self.size, size=batch_size)`

This line of code samples a list of random indices **with replacement**. Would this cause any issues in training if the batch occasionally has multiple transitions that in reality came from one experience step? In a recent DQN implementation I wrote, I used the following line to generate a random list of indices without replacement:

`rand_idxs = torch.from_numpy(np.random.choice(np.arange(self.size), size=batch_size, replace=False))`

**Comment by sfujim** [comment]
Sampling with replacement is standard practice and preferable due to lower computational overhead. I'm not sure if there's a performance difference, but I would assume it would be negligible due to the size of the replay buffer/likelihood of sampling the same transition multiple times.
