### ISSUE TITLE
Are you interested in image input with convolutional networks architecture?

### ISSUE THREAD

**Issue by gouxiangchen** [sfujim/TD3#18]
Thanks for your awsome code!

I have tried DDPG in gym environments and got good results with fully connected netwroks

but when I use the RGB array (several frames stacked in grayscale) offered by gym.render() to train a convolutional actor/critic networks, it seems to be failed even if much longger training than fully connected networks...

I wonder if it is impossible for DDPG to train convolutional networks? Or are you intersted in implementing a variant with convolutional network?

Thanks again !

**Comment by sfujim** [comment]
I believe the [original DDPG paper](https://arxiv.org/abs/1509.02971) has results on image-based tasks, so it is definitely possible, but I suspect it will require careful architecture selection to get things to work. As a starting point, here's a [recent paper](https://arxiv.org/abs/1910.01741) with results on similar tasks from images, using more sophisticated methods than DDPG. 

Unfortunately, in the short term I don't intend on implementing an image-based version, but it's not a bad idea for the future :^)
