### ISSUE TITLE
Great work. Just a quick question.

### ISSUE THREAD

**Issue by hohoCode** [sfujim/TD3#2]
Great work! Thanks for the codes. 

Just quick questions on your three great contributions (DP, TPN, CDQ), have you ever tried the three on discrete-action-space games (just typical ones like SpaceInvader or KungFu or Seaquest etc.)? And are the three tricks providing improvement as well ? Since in the last paragraph of your paper it is mentioned that the three contributions can also be utilized for discrete-action games. 

Thanks again.

**Comment by sfujim** [comment]
Hi,

What I had in mind when I wrote that, was that my modifications are orthogonal to other improvements, so they could be all combined together, not necessarily on discrete action games. 

That being said, I've done some testing with discrete actions, but nothing on atari games, so I can't say too much. In general, I found CDQ to be more effective than Double DQN if the target network was updated frequently, but at a higher computational cost. Some mix between the two, taking the min between the current and target network, could be interesting. Target policy smoothing makes less sense when you can't directly interpolate between actions (i.e. you can't say which actions are "similar" without hand-coding it), although deep SARSA has been shown to be effective in some cases. And of course delaying the policy update only applies in an actor-critic setting. 

Glad you enjoyed the work!

**Comment by hohoCode** [comment]
Thanks for the reply and it is great! Just wondering could you please illustrate the 'mix' as mentioned just a little bit more? Is this what you mean: 'The 'Mix' between CDQ and Double Q'? 
Given: "CDQ to be more effective than Double Q.. if the target network was updated frequently... Some mix between the two, taking the min between the current and target network."

Thanks again.
