### ISSUE TITLE
training a loaded model seems to reset model parameters

### ISSUE THREAD

**Issue by timkoning17** [sfujim/TD3#20]
When loading a pretrained model for further training,  the performance during training seems to have resetted with respect to the pretrained model. Bypassing the train function 

policy.train(replay_buffer, args.batch_size,mean_action,scale)

does result in the performance corresponding to the trained model.
policy.train seems to reset parameters somehow, but i can't seem to find how or where.

**Comment by sfujim** [comment]
Uhhh, I will take a look at this soon. Tbh I wasn't very careful with this part of the code. Although, I will say that if you train a pre-trained model, since the replay buffer will be empty the performance should deteriorate. Adam is also not saved atm so this isn't proper checkpointing either way.

**Comment by timkoning17** [comment]
isn't Adam saved by the line: 
torch.save(self.critic_optimizer.state_dict(), filename + "_critic_optimizer")

since critic_optimizer is 

self.critic_optimizer = torch.optim.Adam(self.critic.parameters(), lr=1e-3)

**Comment by sfujim** [comment]
Oh woops, you are correct, I forgot I added that. Either way the replay buffer isn't saved and learning from a near empty buffer may hurt performance.

**Comment by timkoning17** [comment]
I found the issue: While loading, the actor and critic network are loaded. However, the target actor and target critic network are copied from the random initialized actor and critic during the initialization. The network weights from actor and critic need to be copied to target actor and critic after initialization.

adding these lines to the def load function seems to do the trick: 

self.actor_target = copy.deepcopy(self.actor)
self.critic_target = copy.deepcopy(self.critic)


ps. I don't think the empty replay buffer is a problem, since it only starts to train if
"if t >= args.start_timesteps: "
Therefore the replay buffer will first fill itself before training

**Comment by sfujim** [comment]
Great! Thanks for figuring that out, much appreciated.
