### ISSUE TITLE
some issues about gaussian noise in td3.py

### ISSUE THREAD

**Issue by sorryformyself** [sfujim/TD3#22]
I've noticed that in Td3.py, line 112:

`noise = (
				torch.randn_like(action) * self.policy_noise
			)`

When i see the paper, i found that the gaussian noise before adding to target action should follow N(0, 0.2). Here the 0.2 (self.policy_noise) is used in stddev. 

In your code it's used as multiplication outside the distribution, which will turn the distribution to N(0,0.04). Maybe it's just your implementation? Does this distribution affect the result a lot?

**Comment by sfujim** [comment]
Good point. This is the intended outcome (standard devation = 0.2). I guess the notation N(0,0.2) is iffy since it may imply variance = 0.2, but numpy takes (mean, standard deviation) as input. Sorry for the confusion.
