### ISSUE TITLE
policy update freq in DDPG & OurDDPG

### ISSUE THREAD

**Issue by xubo92** [sfujim/TD3#26]
Hi @sfujim ,

Thanks a lot for your great work! They are really solving some practical problem.

One thing I notice in the main.py function is the policy update frequency for DDPG and OurDDPG. Do they both update at each time step after collect enough data in buffer? Would it be too frequent? I also check the implementation in [Openai Spinup](**https://github.com/openai/spinningup/blob/master/spinup/algos/pytorch/ddpg/ddpg.py**), they update every a few steps. 
So I wonder if there is any special reason behind it, about update both actor and critic in each step?

Thanks a lot!

Best,
Xubo

**Comment by sfujim** [comment]
In the original DDPG paper, they update once at every time step. 

I looked quickly at Spinning Up's implementation and it appears if they update every X steps, they apply X updates, so the average number of updates per timestep is 1 either way, so this shouldn't make a difference in performance. Hope that answers your question!
