### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by zhaoweiqi626** [sfujim/TD3#27]
When I tried running:
`python3 main.py --env HalfCheetah-v2`
such error happened:

> root@ubuntu:/test/TD3-master# python3 main.py --env HalfCheetah-v2
  File "main.py", line 30
    print(f"Evaluation over {eval_episodes} episodes: {avg_reward:.3f}")
                                                                      ^
SyntaxError: invalid syntax

so I guess there are problems with my environment,could you tell me the specific environment?

**Comment by sfujim** [comment]
f-strings were introduced in Python 3.6, so you shouldn't have any issues with Python 3.6+. I just ran it with Python 3.7.3 directly after a git clone with no issues.
