### ISSUE TITLE
Minimum and Array-like Actions

### ISSUE THREAD

**Issue by beelerchris** [sfujim/TD3#28]
The current algorithm assumes `env.action_space.low = -env.action_space.high` and `env.action_space.high[0] = env.action_space.high[i]` for all `i`, which is not the case for all environments.

**Comment by beelerchris** [comment]
Please see the latest Pull request (#29) for changes I have made to correct this.

**Comment by sfujim** [comment]
Thank you for your effort! I'm mainly using this repo as a reference implementation for those who want to reproduce the paper on benchmark environments, which use symmetry in the action space. This is an additional level of detail for more specific use-cases, so I'd prefer to leave it as is.
