### ISSUE TITLE
Worry about the convergence proof

### ISSUE THREAD

**Issue by deeplearnerJHB** [sfujim/TD3#30]
Thanks for your impressive work very much. Unfortunately, I have some worries in my current work. I beg you to give me some guidance.

In my work, I try to improve your clipped double q-learning and want to get its convergence property.

In our algorithm description, for tabular version (discrete action), we randomly update one q-function. And for continuous action version, I follow your updating design. 

However, I just prove that if our improved clipped double q-learning uses the same update mechanism like what you do in the paper, it can converge to the optimal action value. For the case that randomly updating one q-function, I haven't make a proof till now.

Whether I can say that we make the convergence proof about our improved clipped double q-learning in the paper? In the proof part (in Appendix), we will describe the difference between both updating methods.

Or, can you guide me what kind of the description is better? 

Thank you again!

**Comment by sfujim** [comment]
I'm not sure I'm fully following your question but there's a proof for randomly updating Q functions in the original Double Q-learning paper. Maybe that can help you.
