### ISSUE TITLE
Hi, i made re-implementation using yours but it doesn't work.

### ISSUE THREAD

**Issue by seolhokim** [sfujim/TD3#32]
It is only 165 lines with Gym Environment "Pendulum-v0".

I know it is sorry to ask you this. but it is so hard to figure out what went wrong.

If you have enough time, plz check my [repo](https://github.com/seolhokim/The-Easiest-TD3-using-pytorch-in-Pendulum/blob/master/TD3.py).

Regards.

**Comment by sfujim** [comment]
I don't really have time to comb through your code unfortunately but I'm happy to answer questions about this repo. Best of luck.
