### ISSUE TITLE
question about random seeds

### ISSUE THREAD

**Issue by mantle2048** [sfujim/TD3#36]
hi, I tried several experiments and found that even after setting the same random seed, the results are different each time. This confuses me. After debugging, I found that in the main.py 

action = env.action_space.sample()

This line will sample different actions every time, so I want to ask whether gym.action_space should also set the same random seed?

**Comment by ChenDRAG** [comment]
It's common in drl that you get different results using different random seeds. That's why in the paper people usually run the scripts using several(like 10) seeds and then average them.

**Comment by chelsea0x3b** [comment]
FYI for people in the future - env.action_space has a separate RNG than the environment. so if you truly want reproducibility, you should do:

```
env.seed(seed)
env.action_space.seed(seed)
```

**Comment by sfujim** [comment]
Thanks for figuring this out! I've updated the code to include this detail.
