### ISSUE TITLE
state should be next state in algorithm description in the paper

### ISSUE THREAD

**Issue by alito** [sfujim/TD3#5]
If I'm reading the paper and the code right, I think the line that sets ã in the algorithm description in the paper (v2) should be ã = pi sub phi' (s') + epsilon instead of pi sub phi' (s) + epsilon. Right?

(Apologies if this isn't the best way to report bugs in the paper. Feel free to delete. Also, many many thanks for publishing the code)

**Comment by sfujim** [comment]
Yes, this is correct. I've submitted a new version to arXiv along with several other (very minor) changes and clarifications. Thanks!
