### ISSUE TITLE
does overestimate occurs in advantage actor-critic？

### ISSUE THREAD

**Issue by ToTheMonn** [sfujim/TD3#7]

**Comment by sfujim** [comment]
Yes it should, but as it's not studied in this paper, I can't say if the overestimation is significant or if it impacts the performance of the algorithm, especially since it uses n-step estimates.

**Comment by ToTheMonn** [comment]
I am confused about why the value of underestimated actions will not be explicitly propagated
through the policy update?

**Comment by sfujim** [comment]
Informally, the policy update pushes the policy to avoid underestimated actions.
